name: Ubuntu

on:
  workflow_call:
    inputs:
      artifact_id:
        description: 'Unique identifier for artifacts'
        required: true
        type: string
        
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci_test_gcc:
    runs-on: ubuntu-latest
    container: gcc:14
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@28983e0d3955dba2bb0a6810caae0c6cf268ec0c # v4.0.0
      - name: Run CMake
        run: cmake -S . -B build -DJSON_CI=On
      - name: Build
        run: cmake --build build --target ci_test_gcc

      - name: Upload Test Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unit_tests_results
          path: ubuntu/



  ubuntu_artifact:
    runs-on: ubuntu-latest
    needs: [ci_test_gcc]
    steps:
      - name: Generate ubuntu artifact
        run: |
          echo "Generating ubuntu artifact..."
          mkdir -p ubuntu
          echo "ubuntu processed for ${{ inputs.artifact_id }}" > ubuntu/ubuntu.txt

      - name: Upload ubuntu artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_id }}
          path: ubuntu/
